# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(verbose_name='event ID')),
                ('title', models.CharField(max_length=550, null=True, verbose_name='Title')),
                ('text', models.TextField(null=True, verbose_name='Description')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Time and Date')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='rssmodel',
            name='tags',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rss.Tags', verbose_name='Tags'),
        ),
    ]
