# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20170924_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssmodel',
            name='event_id',
            field=models.IntegerField(null=True, verbose_name='event ID'),
        ),
    ]
